
#General settings of Crash Assistant mod.
[general]
	#Link which will be opened in browser on request_help_button pressed.
	help_link = "https://discord.gg/allthemods"
	#Show gui on minecraft crashed on modloading and FML error screen displayed.
	show_on_fml_error_screen = true
	#Close old CrashAssistantApp if it's still running when starting a new instance of Minecraft, to avoid confusing player with window from old crash.
	kill_old_app = true
	#If options.txt doesn't exist, the default language will be used.
	default_lang = "en_us"
	#Append comment text with notice about sending screenshot of this gui tells nothing to modpack creators.
	show_dont_send_screenshot_of_gui_notice = true
	#List of blacklisted log files. This files won't show in GUI logs list.
	blacklisted_logs = ["CrashAssistant: latest.log"]

#Here you can configure debug options for easier configuration of the mod.
[debug]
	#Setting this value to one of listed here, will crash the game in order to show/debug gui.
	#NONE - default value, no crash. You can always crash game by holding vanilla F3+C keybind or '/crash_assistant crash' command
	#MIXIN_SETUP - will crash game on Mixin setup. Crash report not generated.
	#MOD_LOADING - will crash game on load of this mod. Can be used to show FML error screen. Crash report generated.
	#GAME_STARTED - will crash game on first tick of TitleScreen. Crash report generated.
	crash_game_on_event = "NONE"

#Here you can change text of lang placeHolders.
#Also you can change any text in lang files.
#You don't need to modify jar. You can change it in config/crash_assistant/lang. For more info read README.md file located where.
[text]
	#$CONFIG.text.support_name$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "gui.request_help_button": "Request help in the $CONFIG.text.support_name$"
	support_name = "ATM10 Support Channel"
	#$CONFIG.text.support_place$ in lang files will be replaced with this value.
	support_place = "#atm10-techsupport channel"
	#$CONFIG.text.modpack_name$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "gui.title_crashed_with_report": "Oops, $CONFIG.text.modpack_name$ crashed!"
	#Supports Better Compatibility Checker integration. You can use $BCC.modpackName$, $BCC.modpackVersion$, etc and it will be replaced with value from BCC config.
	modpack_name = "$BCC.modpackName$ - $BCC.modpackVersion$"

#Settings of modlist feature.
#Adds in generated msg block about which mods modpack user added/removed/updated.
#Also you can see diff by running '/crash_assistant modlist diff' command.
[modpack_modlist]
	#Enable feature.
	enabled = true
	#nicknames of players, who considered as modpack creator.
	#Only this players can overwrite modlist.json
	#If this feature is enabled and this array is empty, will be appended with nickname of current player.
	modpack_creators = ["whatthedrunk","Uncandango"]
	#If enabled, modlist.json will be overwritten on every launch(first tick of TitleScreen),
	#then game is launched by modpack creator.
	#So you won't forget to save it before publishing.
	#If you want to save manually: disable this and use '/crash_assistant modlist save' command.
	auto_update = false

#Settings of '/crash_assistant crash' command feature.
[crash_command]
	#Enable feature.
	enabled = false
	#To ensure the user really wants to crash the game, the command needs to be run again within this amount of seconds.
	#Set to <= 0 to disable the confirmation.
	seconds = 10

#Settings of message generated by Upload all button
[generated_message]
	#This text will be under "$CONFIG.text.modpack_name$ crashed!" in generated message by Upload all button.
	#You can include:
	#   * some form, which users should fill out.
	#   * additional information like Minecraft version, etc.
	text_under_crashed = ""
	#Warning: if "general.help_link" is default (equals https://discord.gg/moddedmc), this value will be ignored and custom hardcoded message used due to request of ModdedMC discord administration.
	#Leave empty to prevent showing this warning message.
	#With this option you can notify user about something related with posting generated message.
	#For example if they need to fill some option from "generated_message.text_under_crashed", etc.
	#Supports html formatting, placeholders.
	warning_after_upload_all_button_press = ""
	#Crash Assistant splits the log into a head and tail of 25,000 lines each if the log exceeds mclo.gs limits (10 MB or 25,000 lines).
	#Add an explanation at the bottom of the generated message about why log was split.
	generated_msg_includes_info_why_split = false

