blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Feature Request
    url: https://github.com/AllTheMods/ATM-10/discussions/categories/modpack-content
    about: "Create a discussion about your new feature/suggestion"
  - name: ğŸ Mod Bug
    url: https://github.com/AllTheMods/ATM-10/blob/main/MOD_ISSUES.md
    about: "List of Mod's Issue pages"
  - name: "â“ I don't know, I just need help"
    url: https://discord.gg/allthemods
    about: "Join our Discord channel: #atm10-techsupport"
