#Base energy storage in Joules of: Heat Generator
#Range: 1 ~ 9223372036854775807
heatGenerator = 160000
#Base energy storage in Joules of: Bio-Generator
#Range: 1 ~ 9223372036854775807
bioGenerator = 160000
#Base energy storage in Joules of: Solar Generator
#Range: 1 ~ 9223372036854775807
solarGenerator = 96000
#Base energy storage in Joules of: Advanced Solar Generator
#Range: 1 ~ 9223372036854775807
advancedSolarGenerator = 2500000
#Base energy storage in Joules of: Wind Generator
#Range: 1 ~ 9223372036854775807
windGenerator = 200000
