#Base energy storage in Joules of: Enrichment Chamber
#Range: 1 ~ 9223372036854775807
enrichmentChamber = 20000
#Base energy storage in Joules of: Osmium Compressor
#Range: 1 ~ 9223372036854775807
osmiumCompressor = 80000
#Base energy storage in Joules of: Combiner
#Range: 1 ~ 9223372036854775807
combiner = 40000
#Base energy storage in Joules of: Crusher
#Range: 1 ~ 9223372036854775807
crusher = 20000
#Base energy storage in Joules of: Metallurgic Infuser
#Range: 1 ~ 9223372036854775807
metallurgicInfuser = 20000
#Base energy storage in Joules of: Purification Chamber
#Range: 1 ~ 9223372036854775807
purificationChamber = 80000
#Base energy storage in Joules of: Energized Smelter
#Range: 1 ~ 9223372036854775807
energizedSmelter = 20000
#Base energy storage in Joules of: Digital Miner
#Range: 1 ~ 9223372036854775807
digitalMiner = 50000
#Base energy storage in Joules of: Electric Pump
#Range: 1 ~ 9223372036854775807
electricPump = 40000
#Base energy storage in Joules of: Chargepad
#Range: 1 ~ 9223372036854775807
chargepad = 2048000
#Base energy storage in Joules of: Rotary Condensentrator
#Range: 1 ~ 9223372036854775807
rotaryCondensentrator = 20000
#Base energy storage in Joules of: Chemical Oxidizer
#Range: 1 ~ 9223372036854775807
chemicalOxidizer = 80000
#Base energy storage in Joules of: Chemical Infuser
#Range: 1 ~ 9223372036854775807
chemicalInfuser = 80000
#Base energy storage in Joules of: Chemical Injection Chamber
#Range: 1 ~ 9223372036854775807
chemicalInjectionChamber = 160000
#Base energy storage in Joules of: Electrolytic Separator
#Range: 1 ~ 9223372036854775807
electrolyticSeparator = 160000
#Base energy storage in Joules of: Precision Sawmill
#Range: 1 ~ 9223372036854775807
precisionSawmill = 20000
#Base energy storage in Joules of: Chemical Dissolution Chamber
#Range: 1 ~ 9223372036854775807
chemicalDissolutionChamber = 160000
#Base energy storage in Joules of: Chemical Washer
#Range: 1 ~ 9223372036854775807
chemicalWasher = 80000
#Base energy storage in Joules of: Chemical Crystallizer
#Range: 1 ~ 9223372036854775807
chemicalCrystallizer = 160000
#Base energy storage in Joules of: Seismic Vibrator
#Range: 1 ~ 9223372036854775807
seismicVibrator = 20000
#Base energy storage in Joules of: Pressurized Reaction Chamber
#Range: 1 ~ 9223372036854775807
pressurizedReactionBase = 2000
#Base energy storage in Joules of: Fluidic Plenisher
#Range: 1 ~ 9223372036854775807
fluidicPlenisher = 40000
#Base energy storage in Joules of: Laser
#Range: 1 ~ 9223372036854775807
laser = 10000000
#Base energy storage in Joules of: Laser Amplifier
#Range: 1 ~ 9223372036854775807
laserAmplifier = 5000000000
#Base energy storage in Joules of: Laser Tractor Beam
#Range: 1 ~ 9223372036854775807
laserTractorBeam = 5000000000
#Base energy storage in Joules of: Formulaic Assemblicator
#Range: 1 ~ 9223372036854775807
formulaicAssemblicator = 40000
#Base energy storage in Joules of: Teleporter
#Range: 1 ~ 9223372036854775807
teleporter = 5000000
#Base energy storage in Joules of: Modification Station
#Range: 1 ~ 9223372036854775807
modificationStation = 40000
#Base energy storage in Joules of: Isotopic Centrifuge
#Range: 1 ~ 9223372036854775807
isotopicCentrifuge = 80000
#Base energy storage in Joules of: Nutritional Liquifier
#Range: 1 ~ 9223372036854775807
nutritionalLiquifier = 40000
#Base energy storage in Joules of: Nucleosynthesizer. Also defines max process rate.
#Range: 1 ~ 9223372036854775807
antiprotonicNucleosynthesizer = 1000000000
#Base energy storage in Joules of: Pigment Extractor
#Range: 1 ~ 9223372036854775807
pigmentExtractor = 40000
#Base energy storage in Joules of: Pigment Mixer
#Range: 1 ~ 9223372036854775807
pigmentMixer = 80000
#Base energy storage in Joules of: Painting Machine
#Range: 1 ~ 9223372036854775807
paintingMachine = 40000
#Base energy storage in Joules of: SPS Port. Also defines max output rate.
#Range: 1 ~ 9223372036854775807
spsPort = 1000000000
#Base energy storage in Joules of: Dimensional Stabilizer
#Range: 1 ~ 9223372036854775807
dimensionalStabilizer = 40000
