#General settings
[general]
	#The CurseForge project ID for the modpack
	# Default: 0
	# Range: > 0
	modpackProjectID = 925200
	#The name of the modpack
	modpackName = "All the Mods 10"
	#The version of the modpack
	modpackVersion = "2.21"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
