#Enable No Startup Messages module
noStartupMessagesEnabled = true
#A list of word sequences that if contained in a message will be stopped.
noStartupMessagesMessages = ["This game is using an alpha build of Ender IO", "The Mekanism Team", "Thanks for using", "Mekanism is currently in alpha"]
#Disable recipe advancements
disableRecipeAdvancements = true

